name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Adjust as per your project requirements

    - name: Install dependencies
      run: npm ci
      working-directory: ./my-react-website  # Adjust to the path where package-lock.json is located

    - name: Run tests
      run: npm test
      working-directory: ./my-react-website

