name: Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check for package-lock.json
        id: check-lock-file
        run: |
          if [ ! -f package-lock.json ]; then
            echo "::set-output name=exists::false"
          else
            echo "::set-output name=exists::true"
          fi

      - name: Install dependencies (CI)
        if: steps.check-lock-file.outputs.exists == 'true'
        run: npm ci

      - name: Install dependencies (fallback)
        if: steps.check-lock-file.outputs.exists == 'false'
        run: npm install

      - name: Run tests
        run: npm test
